include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
  enable-experiment:
    - non-nullable

linter:
  rules:
    - camel_case_types