name: great_list_view
description: A Flutter package that enhance the standard list view with implicit
  animations on changes and so on. See README.md file.
version: 0.1.5
homepage: https://github.com/DavideBelsole/great_list_view
repository: https://github.com/DavideBelsole/great_list_view

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  diffutil_dart: ^3.0.0
  flutter:
    sdk: flutter
  worker_manager: ^4.4.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
